### ISSUE TITLE
Server - Create Data Models for Crop and User

### ISSUE THREAD

**Issue by yassinej** [chingu-voyage4/Geckos-Team-12#54]
Implement 2 mongosse data models for Crop and User.
Let's agree on next meeting

**Comment by HixOba** [comment]
Please review

**Comment by yassinej** [comment]
Crop Model: _id, name: String, category: String, image_url:String, short_desc:String, difficulty_level: String,  best_season: String, climate: String.
User Model: _id, username: , password, growingCrops: list of crops_id, score:
